Added xlabel= kwarg to mpf.plot() #427
matplotlib/mplfinance pull request #564
Opened 2022-10-21 19:14 UTC by vedant-gawande

Please merge this repo as you can see i have done the work as per requirement

2022-10-21 21:30 UTC, DanielGoldfarb commented
@vedant-gawande 
Ved,
Thanks so much for contributing.  At a glance it looks good.  I'm short on time for this project today, but will look into merging this early next week.  All the best.  --Daniel

2022-10-21 21:31 UTC, DanielGoldfarb commented
issue #427

2022-10-22 11:34 UTC, vedant-gawande commented
> @vedant-gawande Ved, Thanks so much for contributing. At a glance it looks good. I'm short on time for this project today, but will look into merging this early next week. All the best. --Daniel

Yeah sure sir,
No problem

2022-10-28 16:50 UTC, DanielGoldfarb commented on src/mplfinance/plotting.py
> +                                        'Validator'   : lambda value: isinstance(value,str) },
A block of code, similar to this, needs to be also added to `_valid_addplot_kwargs()` ... approximately [**here**](https://github.com/matplotlib/mplfinance/blob/master/src/mplfinance/plotting.py#L1300-L1301).

2022-10-28 16:51 UTC, DanielGoldfarb commented on src/mplfinance/plotting.py
> +    if (apdict['xlabel'] is not None):
This will not work until the new kwarg is ***also*** added to `_valid_addplot_kwargs()` (as noted above).
Thanks.

2022-10-28 16:51 UTC, DanielGoldfarb requested changes
see comments.  please make minor change requested and push to your fork (will automatically propagate to the PR).

2022-10-31 21:01 UTC, DanielGoldfarb commented
It turns out that apparently this was not tested at all.   A little bit of testing showed that it was not working for all cases where the main plot is *not* the bottom-most panel.   
1. In panels mode, the `xlabel` should always be on the bottom panel, and it makes no sense for addplot to support xlabel (since it will always be on the bottom-most panel).  Therefore moved xlabel implementation into `_set_ticks_on_bottom_panel_only()` when in panels mode.  
2. In external axes mode, the user can always call `Axes.set_xlabel()` directly on whichever axes they choose, so again no need to support xlabel in addplot.

This changes were made and merged into the PR.

@vedant-gawande   Thank you for contributing to mplfinance!   Wishing you all the best.

2022-10-31 21:02 UTC, merged